### ISSUE TITLE
请问怎么解析event log中的data怎么进一步解析成地址和字符串呢？

### ISSUE THREAD

**Issue by hardyzp** [yukaige/web3.php#1]

**Comment by yukaige** [comment]
event log 第一个参数为Event名称，可以用Contract的decodeEvent解析，其他的表示地址和int的传参，去0即可。data中的元素是用0分割的，可以拆出来挨个解析，字符串部分可以用Untils::hexToString()解析，不过目前这个方法会有填充多余字符的bug，临时解决方案可以用正则匹配下。

**Comment by zpcodemen** [comment]
> event log 第一个参数为Event名称，可以用Contract的decodeEvent解析，其他的表示地址和int的传参，去0即可。data中的元素是用0分割的，可以拆出来挨个解析，字符串部分可以用Untils::hexToString()解析，不过目前这个方法会有填充多余字符的bug，临时解决方案可以用正则匹配

**Comment by hardyzp** [comment]
ok。了解
